apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      containers:
      - name: teastore-db
        image: descartesresearch/teastore-db
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: teastore-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-registry
  labels:
    app: teastore
    run: teastore-registry
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-registry
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-registry
    spec:
      containers:
      - name: teastore-registry
        image: alirezagoli/teastore-registry
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE_NAME
          value: "teastore-registry"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: USE_POD_IP
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-registry
  labels:
    app: teastore
    run: teastore-registry
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
  labels:
    app: teastore
    run: teastore-persistence
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      containers:
      - name: teastore-persistence
        image: alirezagoli/teastore-persistence
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE_NAME
          value: "teastore-persistence"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        - name: DB_HOST
          value: "teastore-db"
        - name: DB_PORT
          value: "3306"
        resources:
          requests:
            cpu: "1000m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 2
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 10
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            port: 8080
          failureThreshold: 300
          periodSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
  labels:
    app: teastore
    run: teastore-auth
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-auth
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-auth
    spec:
      containers:
      - name: teastore-auth
        image: alirezagoli/teastore-auth
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE_NAME
          value: "teastore-auth"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 2
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 10
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            port: 8080
          failureThreshold: 300
          periodSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
  labels:
    app: teastore
    run: teastore-image
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      containers:
      - name: teastore-image
        image: alirezagoli/teastore-image
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE_NAME
          value: "teastore-image"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        resources:
          requests:
            cpu: "1000m"
            memory: "1024Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 2
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 10
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            port: 8080
          failureThreshold: 300
          periodSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-recommender
  labels:
    app: teastore
    run: teastore-recommender
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-recommender
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-recommender
    spec:
      containers:
      - name: teastore-recommender
        image: alirezagoli/teastore-recommender
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE_NAME
          value: "teastore-recommender"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        resources:
          requests:
            cpu: "1000m"
            memory: "1024Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 2
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 10
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            port: 8080
          failureThreshold: 300
          periodSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-webui
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-webui
    spec:
      containers:
      - name: teastore-webui
        image: alirezagoli/teastore-webui
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE_NAME
          value: "teastore-webui"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP   
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        resources:
          requests:
            cpu: "1000m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 2
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 10
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            port: 8080
          failureThreshold: 300
          periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    run: teastore-webui
